// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "compeerx1.h"

/////////////////////////////////////////////////////////////////////////////
// CCompeerx1

IMPLEMENT_DYNCREATE(CCompeerx1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCompeerx1 properties

/////////////////////////////////////////////////////////////////////////////
// CCompeerx1 operations
