//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSports.OVREQPlugin.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInfo", Namespace="http://schemas.datacontract.org/2004/07/ScoreMonitor")]
    [System.SerializableAttribute()]
    public partial class BaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventName {
            get {
                return this.EventNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNameField, value) != true)) {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HorseName {
            get {
                return this.HorseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HorseNameField, value) != true)) {
                    this.HorseNameField = value;
                    this.RaisePropertyChanged("HorseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFName {
            get {
                return this.MFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MFNameField, value) != true)) {
                    this.MFNameField = value;
                    this.RaisePropertyChanged("MFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchName {
            get {
                return this.MatchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchNameField, value) != true)) {
                    this.MatchNameField = value;
                    this.RaisePropertyChanged("MatchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Noc {
            get {
                return this.NocField;
            }
            set {
                if ((object.ReferenceEquals(this.NocField, value) != true)) {
                    this.NocField = value;
                    this.RaisePropertyChanged("Noc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiderName {
            get {
                return this.RiderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderNameField, value) != true)) {
                    this.RiderNameField = value;
                    this.RaisePropertyChanged("RiderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMonitor")]
    public interface IMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/RecevieBaseInfoTable", ReplyAction="http://tempuri.org/IMonitor/RecevieBaseInfoTableResponse")]
        bool RecevieBaseInfoTable(AutoSports.OVREQPlugin.ServiceReference1.BaseInfo bit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/RecevieJudgeTable", ReplyAction="http://tempuri.org/IMonitor/RecevieJudgeTableResponse")]
        bool RecevieJudgeTable(System.Data.DataTable jt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/RecevieScoreTable", ReplyAction="http://tempuri.org/IMonitor/RecevieScoreTableResponse")]
        bool RecevieScoreTable(System.Data.DataTable st);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorChannel : AutoSports.OVREQPlugin.ServiceReference1.IMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorClient : System.ServiceModel.ClientBase<AutoSports.OVREQPlugin.ServiceReference1.IMonitor>, AutoSports.OVREQPlugin.ServiceReference1.IMonitor {
        
        public MonitorClient() {
        }
        
        public MonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RecevieBaseInfoTable(AutoSports.OVREQPlugin.ServiceReference1.BaseInfo bit) {
            return base.Channel.RecevieBaseInfoTable(bit);
        }
        
        public bool RecevieJudgeTable(System.Data.DataTable jt) {
            return base.Channel.RecevieJudgeTable(jt);
        }
        
        public bool RecevieScoreTable(System.Data.DataTable st) {
            return base.Channel.RecevieScoreTable(st);
        }
    }
}
